CC=g++
CFLAGS=-std=c++11
LDFLAGS=-Iinclude

all: task1 task2 task3

task1:
	$(CC) $(CFLAGS) $(LDFLAGS) -o task1.o task1.cpp

task2:
	$(CC) $(CFLAGS) $(LDFLAGS) -o task2.o task2.cpp

task3:
	$(CC) $(CFLAGS) $(LDFLAGS) -o task3.o task3.cpp

clean:
	rm *.o
