CC=g++
CFLAGS=-std=c++11
LDFLAGS=-I ../lib/glm/

all: task1 task2 task3

task1:
	$(CC) $(CFLAGS) -o task1.o task1.cpp $(LDFLAGS)

task2:
	$(CC) $(CFLAGS) -o task2.o task2.cpp $(LDFLAGS)

task3:
	$(CC) $(CFLAGS) -o task3.o task3.cpp $(LDFLAGS)

clean:
	rm *.o
